service: serverless-boilerplate
provider:
  name: aws
  apiKeys:
    - api_ios
  runtime: nodejs10.16.0 
  environment: 
    NODE_ENV: development
    
functions:
  users-list:
    handler: users.list
    events:
      - http:
          path: /users
          method: get
          cors: true
          private: true
  users-get:
    handler: users.get
    events:
      - http:
          path: /users/{id}
          method: get
          cors: true
          private: true
  users-create:
    handler: users.create
    events:
      - http:
          path: /users
          method: post
          cors: true
          private: true
  users-update:
    handler: users.update
    events:
      - http:
          path: /users/{id}
          method: patch
          cors: true
          private: true
  users-delete:
    handler: users.delete
    events:
      - http:
          path: /users/{id}
          method: delete
          cors: true
          private: true
          
plugins:
  - serverless-iam-roles-per-function
  - serverless-domain-manager
  - serverless-offline


# custom:
#   customDomain:
#     certificateName: '*ioasys.com.br'
#     domainName: 'apiyoube.ioasys.com.br' # Change this to your domain.
#     basePath: 'dev' # This will be prefixed to all routes
#     # stage: ${self:provider.stage}
#     createRoute53Record: true
